title:              Blog Personal de hacking Write-ups
email:              ing.jairocelis@gmail.com
description:        Temas de pentesting y hacking etico
author:             Ch4m17ux
baseurl:            "/"
url:                "https://ch4m17ux.github.io/"

# Social Profiles
twitter_username:   Chamitux
github_username:    ch4m17ux
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
